name: Code Security Scan (Semgrep)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v7
      - name: Run Semgrep
        run: semgrep scan --config .semgrep.yml --config p/security-audit --config p/nodejs --error
